[pytest]
pythonpath = .
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:fastapi.testclient
    ignore::DeprecationWarning:starlette.testclient
    ignore::DeprecationWarning:anyio
    ignore::starlette.exceptions.StarletteDeprecationWarning

