"""initial migration

Revision ID: 14243fe0b746
Revises: 
Create Date: 2026-09-02 16:16:25.138114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14243fe0b746'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('sales', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sales', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sales', 'customer',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.alter_column('sales', 'customer',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sales', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales', 'product_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sales', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
